<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>

<div class="products-grid wishlist product_listing">
    <?php if (count($block->getItems())) : ?>
        <div class="row">
        <?php foreach ($block->getItems() as $item) : ?>
            <div class="col-lg-3 col-md-4 col-12">
                <div data-row="product-item" class="product_div wishlist product-item" id="item_<?= $block->escapeHtmlAttr($item->getId()) ?>">
                    <div class="product-item-info" data-container="product-grid">
                        <?php foreach ($columns as $column) : ?>
                            <?= $column->setItem($item)->toHtml();?>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    <?php else : ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($columns as $column) : ?>
    <?= $column->getAdditionalHtml() ?>
<?php endforeach; ?>
