<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Form $block */
?>
<div id="modal-form" class="callfor-popup">
    <div class="block review-add review_form">
     
        <div class="block-content">
            <?php if ($block->getAllowWriteReviewFlag()) : ?>
                <form action="<?= $block->escapeUrl($block->getAction()) ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
                    <?= $block->getBlockHtml('formkey') ?>
                    <?= $block->getChildHtml('form_fields_before') ?>
                    <fieldset class="fieldset review-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        
                        <div class="review_title">
                            <h6><?= $block->escapeHtml(__("Your opinion matters to us evaluate your ")) ?><?= $block->escapeHtml($block->getProductInfo()->getName()) ?></h6>
                            <p>Los compose obligatorios estar</p>
                        </div>
                        <?php if ($block->getRatings() && $block->getRatings()->getSize()) : ?>
                        <span id="input-message-box"></span>
                        <fieldset class="field required review-field-ratings">
                         
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label><?= __('General Ratings') ?></label>

                                        <div class="control star_radios">
                                            <div class="nested rating pl-0" id="product-review-table">
                                                <?php foreach ($block->getRatings() as $_rating) : ?>
                                                    <div class="field choice review-field-rating">
                                                        
                                                        <div class="control review-control-vote rating">
                                                            <?php $options = $_rating->getOptions();?>
                                                            <?php $iterator = 5; foreach (array_reverse($options) as $_option) : ?>
                                                            <input
                                                            type="radio"
                                                            name="ratings[<?= $block->escapeHtmlAttr($_rating->getId()) ?>]"
                                                            id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                                            value="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                                                            class="radio radio-btn hide"
                                                            data-validate="{'rating-required':true}"
                                                            aria-labelledby="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label <?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label" />
                                                            <label
                                                            class="rating-<?= $block->escapeHtmlAttr($iterator) ?>"
                                                            for="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                                            title="<?= $block->escapeHtmlAttr(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>"
                                                            id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label">
                                                            <span>☆</span>
                                                        </label>
                                                        <?php $iterator--; ?>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                    <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                                </div></div></div></div>



                            </fieldset>
                        <?php endif ?>
                        
                        <div class="field review-field-nickname required row">
                           <div class="col-12">
                               <div class="control form-group">
                                <label for="nickname_field" class="label"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                                
                                <input type="text" name="nickname" id="nickname_field" class="input-text form-control" data-validate="{required:true}" data-bind="value: nickname()" />
                            </div>
                        </div>
                    </div>


                    <div class="field review-field-summary required row">
                       <div class="col-12">
                           <div class="control form-group">
                            <label for="summary_field" class="label"><span><?= $block->escapeHtml(__('Summary')) ?></span></label>
                            
                            
                            <input type="text" name="title" id="summary_field" class="input-text form-control" data-validate="{required:true}" data-bind="value: review().title" />
                        </div>
                    </div>
                </div>

                <div class="field review-field-text required row">
                   <div class="col-12">
                       <div class="control form-group">
                        <label for="review_field" class="label"><span><?= $block->escapeHtml(__('Review')) ?></span></label>
                        <textarea name="detail" id="review_field" class="form-control" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                        
                        
                    </div>
                </div>
            </div>

            
            
        </fieldset>



        <div class="actions-toolbar review-form-actions row mt-5">
            <div class="primary actions-primary col-12">
                <button type="submit" class="action submit primary btn review_btn"><span><?= $block->escapeHtml(__('Submit Review')) ?></span></button>
            </div>
        </div>
    </form>
    <script type="text/x-magento-init">
        {
            "[data-role=product-review-form]": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "#review-form": {
        "Magento_Review/js/error-placement": {},
        "Magento_Review/js/validate-review": {}
    }
}
</script>
<?php else : ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?= $block->escapeHtml(__('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
        </div>
    </div>
<?php endif ?>
</div>
</div>
</div>