<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="col-md-6 col-12">
	<p><?= $block->escapeHtml(__('Get latest the news and don’t miss any update')) ?></p>
</div>
<div class="col-md-6 col-12">
	<form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
				<div class="field newsletter email_box">              
                    <input name="email" type="email" class="form-control" id="newsletter"
					   placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
					   data-mage-init='{"mage/trim-input":{}}'
					   data-validate="{required:true, 'validate-email':true}"
                    />
					<button class="action subscribe primary search_btn"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
						<img src="<?php echo $block->getViewFileUrl('images/email_Send.png'); ?>">
					</button>
				</div>
           
    </form>
</div>