<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<div class="">
    <?= $block->getChildHtml('form_before') ?>
    <form action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/updatePost') ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
                  {"validationURL" : "/checkout/cart/updateItemQty",
                  "updateCartActionContainer": "#update_cart_action_container"}
              }'
              class="form form-cart">
        <?= $block->getBlockHtml('formkey') ?>
        <div style="overflow-y: hidden;" class="table-responsive theme_table wow fadeIn cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
            <?php /* if ($block->getPagerHtml()): ?>
                <div class="cart-products-toolbar cart-products-toolbar-top toolbar" data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?></div>
            <?php endif */ ?>
            <table id="shopping-cart-table"
                   class="cart items data table"
                   data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
                   "updateCartActionContainer": "#update_cart_action_container"}}'>

                <?php foreach ($block->getItems() as $_item): ?>
                    <?= $block->getItemHtml($_item) ?>
                <?php endforeach ?>
            </table>
            <?php if ($block->getPagerHtml()): ?>
                <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar" data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?></div>
            <?php endif ?>
        </div>

    </form>
    <?= $block->getChildHtml('checkout.cart.order.actions') ?>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>

