<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="row text-center">
    <div class="col-12 step_section">
        <div class="cart-empty mb-5">
            <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
            <p><?= /* @escapeNotVerified */ __('You have no items in your shopping cart.') ?></p>
            <p><?php /* @escapeNotVerified */ echo __('Click <a class="Remove_de" href="%1">here</a> to continue shopping.',
                    $block->escapeUrl($block->getContinueShoppingUrl())) ?></p>
            <?= $block->getChildHtml('shopping.cart.table.after') ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Checkout/js/empty-cart": {}
    }
}
</script>