<?php 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$baseUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);

$mediaUrl =  $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<a class="logo logo_section" href="<?php echo $baseUrl ?>" title="" aria-label="store logo">
		<span class="gw-menu-text">
			<img src="<?php echo $mediaUrl.'logo/stores/1/logo_1_.svg' ?>" title="" alt="" width="189" height="64">
		</span>
</a>

<section class="product_Details pb-0 custom_step">
    <div class="container">
        <div class="step_section">
            <div class="row">
                <div class="col-12">
                    <ul class="steppper_page">
                        <li class="step_activ"><span class="step_count">1</span><span class="cart_counter_text"><?= __('Mi Carrito') ?></span></li>
                        <li class=""><span class="step_count">2</span><span class="cart_counter_text"><?= __('Envío') ?></span></li>
                        <li class=""><span class="step_count">3</span><span class="cart_counter_text"><?= __('Pago') ?></span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
