<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\ShopbyBase\Model\FilterSetting $filterSetting */
/** @var \Amasty\Shopby\Block\Navigation\FilterRenderer $block */

$filterUniqId = $block->escapeId(uniqid());
$filterCode = $block->escapeHtml($filterSetting->getFilterCode());
?>

<?php if ($filterSetting->isShowSearchBox(count($filterItems))): ?>
    <?= /* @noEscape */ $block->getSearchForm(); ?>
<?php endif; ?>

<form class="am-ranges"
      data-am-js="ranges"
      data-amshopby-filter="<?= $block->escapeHtml($filterCode);?>"
      data-amshopby-filter-request-var="<?= $block->escapeHtml($block->getFilter()->getRequestVar()); ?>"
      autocomplete="off">
    <ol class="gw-nav gw-nav-list gw-submenu items prod_filter am-filter-items-<?= /* @noEscape */ $filterCode;?>"
        <?php if ($filterSetting->getEnableOverflowScroll() > 0): ?>
            style="max-height:<?= $block->escapeHtml($filterSetting->getEnableOverflowScroll()) ?>px;"
        <?php endif; ?> style="display: block;">
        <?php /** @var \Amasty\Shopby\Model\Layer\Filter\Item $filterItem */?>
        <?php foreach ($filterItems as $filterItem): ?>
            <?php $optionLabel = $filterItem->getOptionLabel(); ?>
            <?php $inputType = !$filterSetting->isMultiselect() ||
            in_array($filterCode, ['rating', 'stock']) ? 'radio' : 'checkbox'?>
        <li class="item"
            data-label="<?= /* @noEscape */ trim(preg_replace('/\s+/', ' ', $block->stripTags($optionLabel))) . ($filterCode == 'rating' ? __(' star(s)') : ''); ?>">
            <?php if ($filterItem->getCount() >= 0): ?>

                <?php $style = ($inputType == 'radio' && !$block->getRadioAllowed())
                || in_array($filterCode, ['rating', 'stock'])  ? 'display: none;' : ''; ?>
                <div class="container-cus-check">
                <input
                        name="amshopby[<?= /* @noEscape */ $block->getFilter()->getRequestVar();?>][]"
                        value="<?= $block->escapeHtml($filterItem->getValueString());?>"
                        type="<?= /* @noEscape */ $inputType;?>"
                        class="custom_filter"
                        style="<?= /* @noEscape */ $style ?>"
                    <?= /* @noEscape */ $block->checkedFilter($filterItem) ? ' checked' : ''; ?>
                />
                 <span class="checkmark"></span>
                </div>

                <a
                    class="am-filter-item-<?= /* @noEscape */ $block->escapeId(uniqid())?>"
                    data-am-js="filter-item-default"
                    href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                    <?= /* @noEscape */ $filterSetting->isAddNofollow() ? ' rel="nofollow"' : '' ?>
                >

                    <span class="label"><?= /* @noEscape */ $optionLabel;?></span>
                    <?php if ($filterSetting->isShowProductQuantities()): ?>
                        <?php //Delete spaces around counter ?>
                        <span class="count"><?= /* @noEscape */ " (".$filterItem->getCount().")" ?></span>
                    <?php endif; ?>
                </a>
            <?php else: ?>
                <span class="label"><?= /* @noEscape */ $optionLabel;?></span>
                <?php if ($filterSetting->isShowProductQuantities()): ?>
                    <?php //Delete spaces around counter ?>
                    <span class="count"><?= /* @noEscape */ " (".$filterItem->getCount().")" ?></span>
                <?php endif; ?>
            <?php endif; ?>
            </li>
        <?php endforeach ?>
    </ol>
</form>

<?php if ($filterSetting->getAddFromToWidget() && isset($fromToConfig) && is_array($fromToConfig)): ?>
    <?= /* @noEscape */ $block->getFromToWidget('default') ?>
<?php endif;?>
