<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Edit $block */
?>
<?php
  $addressbook=$this->getUrl('customer/address/index');
?>
<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<div class="tab-content profile_tab_content" id="v-pills-tabContent">
                  <div class="tab-pane fade show active" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">

<form class="form-address-edit"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
       <div class="row">
            <div class="col-12 col-lg-6">
                <fieldset class="fieldset">
               <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
                <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
                        <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getCustomer())->toHtml() ?>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                                        <label><?= $block->escapeHtml(__('Company')) ?></label>
                                        <input type="text" name="company" id="company" placeholder="Enter Company Name"  class="form-control input_box" value="<?= $block->escapeHtml($block->getAddress()->getCompany()) ?>">

                        </div>
                  </div>
                </div>
                 <div class="row">
                      <div class="col-lg-12">
                         <div class="form-group">
                            <label><?= $block->escapeHtml(__('Phone Number')) ?></label>
                            <input type="text" name="telephone" id="telephone" placeholder="Enter Phone Number"  class="form-control input_box" value="<?= $block->escapeHtml($block->getAddress()->getTelephone()) ?>">
                         </div>
                      </div>
                   </div>
                </fieldset>
            </div>
             <div class="col-12 col-lg-6">
                <fieldset class="fieldset">
               <div class="row">
                  <div class="col-lg-12">
                     <div class="form-group">
                        <?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>
                            <div class="field street required">
                                <label for="street_1" class="label">
                                     <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span>
                                </label>
                            <div class="control">
                            <input type="text"
                                   placeholder="Enter Address"
                                   name="street[]"
                                   value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                                   title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>"
                                   id="street_1"
                                   class="input-text form-control input_box mb-2  <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"/>
                                 <div class="nested">
                                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                                        <?php for ($_i = 1, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i < $_n; $_i++) : ?>
                                                <div class="field additional">
                                                <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                                                    <span><?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?></span>
                                                </label>
                                                    <div class="control">
                                                    <input type="text" placeholder="Enter Address" name="street[]"
                                                           value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                                           title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                                           id="street_<?= /* @noEscape */ $_i + 1 ?>"
                                                           class="input-text form-control input_box mb-2   <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                                    </div>
                                                </div>
                                         <?php endfor; ?>
                                 </div>
                             </div>
                         </div>
                     </div>
                  </div>
               </div>
                         <?php if ($this->helper(\Magento\Customer\Helper\Address::class)->isVatAttributeVisible()) : ?>
                                    <div class="row">
                                          <div class="col-lg-12">
                                             <div class="form-group">
                                                <div class="field taxvat">
                                                <label><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></label>
                                                  <div class="control">
                                                        <input type="text"
                                                           name="vat_id"
                                                           value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                                                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                                                           class="input-text form-control input_box <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('vat_id')) ?>"
                                                           id="vat_id">
                                                    </div>
                                                 </div>
                                             </div>
                                          </div>
                                       </div>
                         <?php endif; ?>

                                     <div class="row">
                                          <div class="col-lg-12">
                                             <div class="form-group">
                                                 <div class="field city required">
                                                         <label class="label"><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></label>
                                                    <div class="control">
                                                        <input type="text"
                                                               placeholder="Enter Address"
                                                           name="city"
                                                           value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                                                           title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                                                           class="input-text form-control input_box <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>"
                                                           id="city">
                                                    </div>

                                                </div>
                                             </div>
                                          </div>
                                       </div>

                                 <div class="row">
                                     <div class="col-lg-12">
                                     <div class="form-group">
                                        <div class="field region required">
                                            <label><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></label>
                                                <div class="control">
                                                    <select id="region_id" name="region_id"
                                                                title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                                                                class="validate-select region_id form-control input_box" <?= /* @noEscape */ !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                                                                <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                                                    </select>

                                                    <input type="text"
                                                           id="region"
                                                           name="region"
                                                           value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                                                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                                                           class="form-control input_box input-text validate-not-number-first <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>

                                                </div>
                                            </div>
                                     </div>
                                  </div>
                               </div>

                                         <div class="row">
                                          <div class="col-lg-12">
                                             <div class="form-group">
                                                 <div class="field country required">
                                                        <label><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></label>
                                                        <div class="control ">
                                                                 <?= $block->getCountryHtmlSelect() ?>
                                                         </div>
                                                </div>
                                             </div>
                                          </div>
                                       </div>
                                <?php if ($block->isDefaultBilling()) : ?>
                                <div class="message info">
                                    <span><?= $block->escapeHtml(__("It's a default billing address.")) ?></span>
                                </div>
                            <?php elseif ($block->canSetAsDefaultBilling()) : ?>
                                <div class="field choice set billing">
                                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                                    <label class="label1" for="primary_billing">
                                        <span><?= $block->escapeHtml(__('Use as my default billing address')) ?></span>
                                    </label>
                                </div>
                            <?php else : ?>
                                <input type="hidden" name="default_billing" value="1" />
                            <?php endif; ?>

                            <?php if ($block->isDefaultShipping()) : ?>
                                <div class="message info">
                                    <span><?= $block->escapeHtml(__("It's a default shipping address.")) ?></span>
                                </div>
                            <?php elseif ($block->canSetAsDefaultShipping()) : ?>
                                <div class="field choice set shipping">
                                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                                    <label class="label1" for="primary_shipping">
                                        <span><?= $block->escapeHtml(__('Use as my default shipping address')) ?></span>
                                    </label>
                                </div>
                            <?php else : ?>
                                <input type="hidden" name="default_shipping" value="1">
                            <?php endif; ?>

            </div>
        </div>
    </fieldset>
                                         <div class="row">
                                            <div class="col-12">
                                                <div class="actions-toolbar">
                                                      <div class="primary">
                                                         <button type="submit"
                                                                class="action save primary btn theme_btn mt-3"
                                                                data-action="save-address"
                                                                title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>">
                                                             <span><?= $block->escapeHtml(__('Save Address')) ?></span>
                                                        </button>
                                                      <a class="btn theme_btn mt-3" href="<?php echo $addressbook ?>"><?php echo $block->escapeHtml(__('Cancel')); ?></a>
                                                      </div>
                                                     </div>
                                            </div>
                                        </div>
</form>
</div>
</div>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
