<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>

<ul class="items gw-nav gw-nav-list gw-submenu">
    <?php foreach ($filterItems as $filterItem) : ?>
        <li class="item init-arrow-down">
            <?php if ($filterItem->getCount() > 0) : ?>
                <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">
                    <?= /* @noEscape */ $filterItem->getLabel() ?>
                    <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                        <span class="count"><?= /* @noEscape */ "( ".(int)$filterItem->getCount()." )" ?>
                            
                    <?php endif; ?>
                </a>
            <?php else :?>
                <?= /* @noEscape */ $filterItem->getLabel() ?>
                <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                    <span class="count"><?= /* @noEscape */ "( ".(int)$filterItem->getCount()." )" ?>
                        
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ul>
