<?php
use Magento\Framework\App\Action\Action;
$populars = $block->getPopularCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
if ($populars && $populars->count()):
	$viewMode = 'grid';
	$imageDisplayArea = 'category_page_grid';
	$showDescription = false;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;   
?>
<div class="bestseller_home">
<div class="row">
	<div class="col-12">
		<div class="pre_order_content">
			<div class="section_title">
				<h2><?= __('Best Sellers'); ?></h2>
				<p></p>
				<span class="bottom_line"></span>
			</div>
		</div>
	</div>	
</div>
 
<div class="product_listing new_product_slider bestseller owl-carousel owl-them popular">
<?php foreach ($populars as $_product) {
	$postParams = $block->getAddToCartPostParams($_product);
?>
	<div class="product_div">
	<?php $orgprice = $_product->getPrice();
								$specialprice = $_product->getSpecialPrice();
								$specialfromdate = $_product->getSpecialFromDate();
								$specialtodate = $_product->getSpecialToDate();
								$today = time();
								if (!$specialprice)
								  $specialprice = $orgprice;
								if ($specialprice< $orgprice) {
									if ((is_null($specialfromdate) &&is_null($specialtodate)) || ($today >= strtotime($specialfromdate) &&is_null($specialtodate)) || ($today <= strtotime($specialtodate) &&is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) { ?>
										<div class="offer">         
											<span class="offer_title"><font style="vertical-align: inherit;"><?= __('Offer') ?> </font></span>
										</div>
									<?php } 
								} ?>
								<?php if($_product->getNewProduct())
								{ ?>
									<div class="new_products">          
										<span class="new_title"><font style="vertical-align: inherit;"><?= __('New') ?> </font></span>
									</div>
								<?php } ?>
		<div class="product_img">
			<a href="<?php echo $_product->getProductUrl(); ?>">
				<?= $block->getImage($_product, $imageDisplayArea)->toHtml() ?>
			</a>
		</div>
		<form data-role="tocart-form" data-product-id="<?= $block->escapeHtml($_product->getId()) ?>" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
			<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
			<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
			<?php echo $block->getBlockHtml('formkey')?>
			<div class="about_pre_product">
				<a href="<?php echo $_product->getProductUrl(); ?>"><h5><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h5></a>
				
				<div class ="custom-merge-div">
					<?php if ($_product->getAttributeText('manufacturer')) { ?>
								<div class="custom-brand-name">
								<?php


									$manufacturerName = $_product->getAttributeText('manufacturer');
									$manufacturerName = strtolower($manufacturerName);


									$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
									$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
									$connection = $resource->getConnection();
									$tableName = $resource->getTableName('emizentech_shopbybrand_items'); //gives table name with prefix

									//Select Data from table
									$sql = "Select name, logo FROM " . $tableName;
									$result = $connection->fetchAll($sql); // gives associated array, table fields as key in array.

									$img = '';
									foreach($result as $res) {
										$brname = strtolower($res['name']);
										if($brname == $manufacturerName) {
											$img = $res['logo'];
										}
									}

									if($img) {
								?>
									<img class="img-responsive" src="<?php echo  $this->getUrl().'pub/media/'.$img ?>" alt="<?php echo $manufacturerName; ?>" height="60px" width="60px" />
								<?php } else { ?>
									<span class="br_name"><?php echo $manufacturerName; ?></span>
								<?php } ?>
								</div>
								<?php } ?>
								<div class="custom_rating_category" style="display: block!important;">
				<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
								</div>
				</div>
				<?php if ($_product->isAvailable()) :?>
										<div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
								<?php endif; ?>
				<div class="butt_price_section">
					<?= $this->getProductPrice($_product); ?>
					<?php $orgprice = $_product->getPrice();
								$specialprice = $_product->getSpecialPrice();
								$specialfromdate = $_product->getSpecialFromDate();
								$specialtodate = $_product->getSpecialToDate();
								$today = time();
								if (!$specialprice)
								  $specialprice = $orgprice;
								if ($specialprice< $orgprice) {
									if ((is_null($specialfromdate) &&is_null($specialtodate)) || ($today >= strtotime($specialfromdate) &&is_null($specialtodate)) || ($today <= strtotime($specialtodate) &&is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) {
										$savingpct = number_format((float)(100*(($orgprice - $specialprice)/$orgprice)), 0);?>
										<div class="money_saved">
											<span class="price-save-label">Ahorra </span>
											<span class="price-save-percent"><?php echo " ".$savingpct." %"?></span>
										</div>
									<?php }
								}?>
					<?php if ($_product->isSaleable()): ?>
						<div class="display_hvr">
							
						<button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                data-role="tocart-form"
                                class="action tocart primary btn theme_btn img_btn"
                                data-product-id = "<?php echo $_product->getId(); ?>"
                                id="add-to-cart-<?php echo $_product->getId(); ?>'">
                            <span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
                        </button>
                            <div class="details_btns_container"
                                 data-mage-init='{"Magento_Catalog/js/modal-form": {"product_id": <?php echo $_product->getId(); ?>}}'
                                 data-product-id = "<?php echo $_product->getId(); ?>">
                                <a class="btn details_btn btn_black_bg">
                                    <?= __('Free withdrawal in store') ?>
                                </a>
                            </div>

						</div>
						<?php else: ?>
								<?php if ($_product->isAvailable()): ?>
									<div class="display_hvr"><div class="stock available btn btn_red"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div></div>
								<?php else: ?>
									<div class="display_hvr"><div class="stock unavailable btn btn_red"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div></div>
								<?php endif; ?>
					<?php endif; ?>
				</div>
			</div>
		</form>
	</div>
<?php
}
?>
</div>
</div>
<script type="text/x-magento-init">
	{
		"[data-role=tocart-form], .form.map.checkout": {
			"catalogAddToCart": {
				"product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
			}
		}
	}
</script>
<?php endif; ?>

<div id="modal-form" class="row" style="display: none">
    <% if (posts) { %>
    <div class="location_list">
        <% if (posts.location_info) { %>
        <% _.each(posts.location_info.location_id, function(text,value) { %>
        <div class="location">
            <% if (posts.location_info.location_img_url) { %>
            <div class="location-info-row" >
                <div class="store_img" >
                    <img src="<%= posts.location_info.location_img_url[value] %>" />
                </div>
                <% } %>
                <% if (posts.location_info) { %>
                <div class="location-info" storepickup_id="<%= posts.location_info.location_id[value] %>">
                    <% if (posts.location_info.location_name) { %>
                    <div class="location-name">
                    <b>
                        <%= posts.location_info.location_name[value] %>
                        </b>
                    </div>
                    <% } %>
                    <% if (posts.location_info.location_address) { %>
                    <div class="location-address">
                        <%= posts.location_info.location_address[value] %>
                    </div>
                    <% } %>
                    <% if (posts.location_info.location_schedule) { %>
                    <div class="location-time">
                        <%= posts.location_info.location_schedule %>
                    </div>
                    <% } %>
                    <% if (posts.location_info.location_phone_num) { %>
                    <div class="location-contact">
                        <%= posts.location_info.location_phone_num[value] %>
                    </div>
                    <% } %>
                </div>
            </div>
            <% } %>
            <% if (posts.stock_info) { %>
            <div class="stock-info">
                <% if (posts.stock_info.status[value] == 1) { %>
                <div class="disponit-icon"> <i class="fa fa-check" aria-hidden="true"></i> Disponible en la tienda</div>
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                        class="popup-addtocart  btn theme_btn img_btn mb-3 action tocart primary">
                    <span><?= $block->escapeHtmlAttr(__('Add to Cart')) ?></span>
                </button>
                <% } %>
                <% if (posts.stock_info.status[value] == 0) { %>
                                    <div class="no-disponit-icon"><i class="fa fa-times" aria-hidden="true"></i> No Disponible </div>
                                <% } %>
                                <% if (typeof posts.stock_info.status[value] == 'undefined') { %>
                                    <div class="no-disponit-icon"><i class="fa fa-times" aria-hidden="true"></i> No Disponible </div>
                                <% } %>
               

            </div>
            <% } %>
        </div>
        <% }) %>
        <% } %>
        <% } %>
    </div>
    <% if (posts.length == 0) { %>
    <div class="location_list">
        <?= __('No Pickup store available.') ?>
    </div>
    <% } %>
</div>

