<?php
use Magento\Framework\App\Action\Action;
$preorders = $block->getBackorderProducts();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
if ($preorders && $preorders->count()):
	$viewMode = 'grid';
	$imageDisplayArea = 'category_page_grid';
	$showDescription = false;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;   
?>
<div class="col-12 col-lg-4 col-md-5">
	<div class="pre_order_content">
		<div class="section_title">
			<h2><?= __('Make Your Pre Order') ?></h2>
			<p><?= __('Book your order before launching and grab it first') ?></p>
			<span class="bottom_line"></span>
		</div>
		<p><?= __('Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an took a galley of type and scrambled it to make a type specimen book.')?></p>
	</div>
</div>

<div class="col-12 col-lg-8 col-md-7">
	<div class="pre_order_slider_main owl-carousel owl-theme">
		<?php foreach ($preorders as $_product) {
			$postParams = $block->getAddToCartPostParams($_product);
			$parentproduct = $block->getConfigParentProduct($_product->getId());
			if(!$parentproduct) {
				$_product = $_product;			
			} else { 
				$_product = $block->getLoadProduct($parentproduct);
			}
		?>
				<div class="pre_order_slider">
					<?php $orgprice = $_product->getPrice();
								$specialprice = $_product->getSpecialPrice();
								$specialfromdate = $_product->getSpecialFromDate();
								$specialtodate = $_product->getSpecialToDate();
								$today = time();
								if (!$specialprice)
								  $specialprice = $orgprice;
								if ($specialprice< $orgprice) {
									if ((is_null($specialfromdate) &&is_null($specialtodate)) || ($today >= strtotime($specialfromdate) &&is_null($specialtodate)) || ($today <= strtotime($specialtodate) &&is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) { ?>
										<div class="offer">         
											<span class="offer_title"><font style="vertical-align: inherit;">Offer </font></span>
										</div>
									<?php } 
								} ?>
								<?php if($_product->getNewProduct())
								{ ?>
									<div class="new_products">          
										<span class="new_title"><font style="vertical-align: inherit;">New </font></span>
									</div>
								<?php } ?>
					<div class="img_container">
						<a href="<?php echo $_product->getProductUrl(); ?>">
							<?= $block->getImage($_product, $imageDisplayArea)->toHtml() ?>
						</a>
					</div>
					<form data-role="tocart-form" data-product-id="<?= $block->escapeHtml($_product->getId()) ?>" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
						<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
						<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
						<?php echo $block->getBlockHtml('formkey')?>
						<div class="about_pre_product">
							<a href="<?php echo $_product->getProductUrl(); ?>"><h5><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h5></a>
							<?php if($_product->getShortDescription()){ ?>
								<p><?php $_product->getShortDescription(); ?></p>
							<?php } ?>
							<span><?= $this->getProductPrice($_product); ?></span>
							<?php if ($_product->isSaleable()): ?>
									<button type="submit" title="<?php echo $block->escapeHtml(__('Pre order')); ?>" data-role="tocart-form" class="action tocart primary btn theme_btn"><span><?php echo $block->escapeHtml(__('Pre order')); ?></span></button>
									<?php /* <a href="javascript:void(0)" onClick="productaddtocart(jQuery(this))"><img src="<?php echo $block->getViewFileUrl('images/cart_white.png'); ?>"></a>
									<a class="bss-quickview hovercart" data-toggle="modal" data-target="#product_quickview" data-quickview-url="" href="javascript:void(0)"><img src="<?php echo $block->getViewFileUrl('images/search_white.png'); ?>"></a> */ ?>								
							<?php else: ?>
									<?php if ($_product->isAvailable()): ?>
										<div class="display_hvr"><div class="stock available btn btn_red"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div></div>
									<?php else: ?>
										<div class="display_hvr"><div class="stock unavailable btn btn_red"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div></div>
									<?php endif; ?>
							<?php endif; ?>
						</div>
					</form>
				</div>	
		<?php
		}
		?>
	</div>
</div>
<script type="text/x-magento-init">
	{
		"[data-role=tocart-form], .form.map.checkout": {
			"catalogAddToCart": {
				"product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
			}
		}
	}
</script>
<?php endif; ?>