<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_MultiInventory
 */
?>
<?php
/**
 * @var \Amasty\MultiInventory\Block\Adminhtml\Warehouse\Tab\Product $block
 */

$numColumns = count($block->getColumns());

?>
<?php if ($block->getCollection()) : ?>
    <?php if ($block->canDisplayContainer()) : ?>

    <div id="<?= $block->escapeHtml($block->getId()) ?>" data-grid-id="<?= $block->escapeHtml($block->getId()) ?>">
    <?php else : ?>
            <?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
    <?php endif; ?>
        <?php $massActionAvailable = $block->getMassactionBlock() && $block->getMassactionBlock()->isAvailable() ?>
        <?php if ($block->getPagerVisibility()
            || $block->getExportTypes()
            || $block->getFilterVisibility()
            || $massActionAvailable
        ) : ?>
            <div class="admin__data-grid-header admin__data-grid-toolbar">
                <div class="admin__data-grid-header-row">
                    <?php if ($massActionAvailable) : ?>
                        <?= $block->getMainButtonsHtml()
                            ? '<div class="admin__filter-actions">' . $block->getMainButtonsHtml() . '</div>'
                            : ''; ?>
                    <?php endif; ?>
                    <?php if ($block->getExportTypes()) : ?>
                        <div class="admin__data-grid-export">
                            <label
                                    class="admin__control-support-text"
                                    for="<?= $block->escapeHtml($block->getId()); ?>_export"
                            >
                                <?= $block->escapeHtml(__('Export to:')); ?></label>
                            <select
                                    name="<?= $block->escapeHtml($block->getId()); ?>_export"
                                    id="<?= $block->escapeHtml($block->getId()); ?>_export"
                                    class="admin__control-select">
                                <?php foreach ($block->getExportTypes() as $_type) : ?>
                                    <option value="<?= $block->escapeHtml($_type->getUrl()); ?>">
                                        <?= $block->escapeHtml($_type->getLabel()); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                            <?= $block->getExportButtonHtml() ?>
                        </div>
                    <?php endif; ?>
                </div>

                <div class="admin__data-grid-header-row <?= $massActionAvailable ? '_massaction' : '';?>">
                    <?php if ($massActionAvailable) : ?>
                        <?= $block->getMassactionBlockHtml() ?>
                    <?php else : ?>
                        <?= $block->getMainButtonsHtml()
                            ? '<div class="admin__filter-actions">' . $block->getMainButtonsHtml() . '</div>'
                            : '';
                        ?>
                    <?php endif; ?>
                    <?php $countRecords = $block->getCollection()->getSize(); ?>

                    <div class="admin__control-support-text">
                        <span id="<?= $block->escapeHtml($block->getHtmlId()) ?>-total-count"
                            <?= /* @noEscape */ $block->getUiId('total-count') ?>
                            <?= /* @noEscape */ $countRecords ?>
                        >
                        </span>
                        <?= $block->escapeHtml(__('records found')); ?>
                        <?php $recordsAddtional = $block->getGeneralTotals(); ?>
                        <?php foreach ($recordsAddtional as $key => $value) : ?>
                            <span
                                    id="<?= $block->escapeHtml($block->getHtmlId()) ?>-total-count<?= /* @noEscape */
                                    $key; ?>"
                                <?= /* @noEscape */
                                $block->getUiId('total-count') ?>
                                    class="header-general"
                            >
                                <b><?= $block->escapeHtml($value['label']); ?>:</b>
                            <?= $block->escapeHtml($value['value']); ?>
                        </span>
                        <?php endforeach; ?>

                        <span id="<?= $block->escapeHtml($block->getHtmlId()) ?>_massaction-count"
                              class="mass-select-info _empty">
                            <strong data-role="counter">0</strong>
                            <span><?= $block->escapeHtml(__('selected')); ?></span>
                        </span>
                    </div>

                    <?php if ($block->getPagerVisibility()) : ?>
                        <div class="admin__data-grid-pager-wrap">
                            <select name="<?= $block->escapeHtml($block->getVarNameLimit()); ?>"
                                    id="<?= $block->escapeHtml($block->getHtmlId())?>_page-limit"
                                    onchange="<?= /* @noEscape */ $block->getJsObjectName() ?>.loadByElement(this)"
                                    class="admin__control-select">
                                <option value="20"<?php if ($block->getCollection()->getPageSize() == 20) : ?>
                                    selected="selected" <?php endif; // @codingStandardsIgnoreLine?>
                                >
                                    20
                                </option>
                                <option value="30"<?php if ($block->getCollection()->getPageSize() == 30) : ?>
                                    selected="selected" <?php endif; // @codingStandardsIgnoreLine?>
                                >
                                    30
                                </option>
                                <option value="50"<?php if ($block->getCollection()->getPageSize() == 50) : ?>
                                    selected="selected" <?php endif; // @codingStandardsIgnoreLine?>
                                >
                                    50
                                </option>
                                <option value="100"<?php if ($block->getCollection()->getPageSize() == 100) : ?>
                                    selected="selected"<?php endif; // @codingStandardsIgnoreLine?>
                                >
                                    100
                                </option>
                                <option value="200"<?php if ($block->getCollection()->getPageSize() == 200) : ?>
                                    selected="selected"<?php endif; // @codingStandardsIgnoreLine?>
                                >
                                    200
                                </option>
                            </select>
                            <label for="<?= $block->escapeHTML($block->getHtmlId())?>
                            <?= $block->escapeHtml($block->getHtmlId())?>_page-limit"
                                   class="admin__control-support-text"><?= $block->escapeHtml(__('per page')); ?>
                            </label>

                            <div class="admin__data-grid-pager">
                                <?php $_curPage = $block->getCollection()->getCurPage() ?>
                                <?php $_lastPage = $block->getCollection()->getLastPageNumber() ?>
                                <?php if ($_curPage > 1) : ?>
                                    <button class="action-previous"
                                            type="button"
                                            onclick="<?= /* @noEscape */ $block->getJsObjectName() ?>
                                                    .setPage('<?= ($_curPage - 1) ?>');
                                                    return false;"
                                    >
                                        <span><?= $block->escapeHtml(__('Previous page')); ?></span>
                                    </button>
                                <?php else : ?>
                                    <button type="button" class="action-previous disabled">
                                        <span><?= $block->escapeHtml(__('Previous page')); ?></span>
                                    </button>
                                <?php endif; ?>
                                <input type="text"
                                       id="<?= $block->escapeHTML($block->getHtmlId())?>_page-current"
                                       name="<?= $block->escapeHtml($block->getVarNamePage()); ?>"
                                       value="<?= /* @noEscape */ $_curPage ?>"
                                       class="admin__control-text"
                                       onkeypress="<?= /* @noEscape */ $block->getJsObjectName() ?>
                                               .inputPage(event, '<?= /* @noEscape */ $_lastPage ?>')"
                                    <?= /* @noEscape */ $block->getUiId('current-page') ?>
                                />
                                <label
                                        class="admin__control-support-text"
                                        for="<?= $block->escapeHTML($block->getHtmlId())?>_page-current">
                                    <?= /* @noEscape */
                                        __(
                                            'of %1',
                                            '<span>' . $block->getCollection()->getLastPageNumber() . '</span>'
                                        )
                                    ?>
                                </label>
                                <?php if ($_curPage < $_lastPage) : ?>
                                    <button type="button"
                                            title="<?= $block->escapeHtml(__('Next page')); ?>"
                                            class="action-next"
                                            onclick="<?= /* @noEscape */ $block->getJsObjectName() ?>
                                                    .setPage('<?= /* @noEscape */($_curPage + 1) ?>');
                                                    return false;"
                                    >
                                        <span><?= $block->escapeHtml(__('Next page')); ?></span>
                                    </button>
                                <?php else : ?>
                                    <button
                                            type="button"
                                            class="action-next disabled"
                                    >
                                        <span><?= $block->escapeHtml(__('Next page')); ?></span>
                                    </button>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
            <table class="data-grid" id="<?= $block->escapeHtml($block->getId()) ?>_table">
                <?php if ($block->getHeadersVisibility() || $block->getFilterVisibility()) : ?>
                    <thead>
                    <?php if ($block->getHeadersVisibility()) : ?>
                        <tr>
                            <?php foreach ($block->getColumns() as $_column) : ?>
                                <?php if ($_column->getHeaderHtml() == '&nbsp;') :?>
                                    <th
                                            class="data-grid-th"
                                            data-column="<?= /* @noEscape */ $_column->getId() ?>"
                                        <?= $_column->getHeaderHtmlProperty() ?>>&nbsp;</th>
                                <?php else : ?>
                                    <?= $_column->getHeaderHtml()?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif; ?>
                    <?php if ($block->getFilterVisibility()) : ?>
                        <tr class="data-grid-filters" data-role="filter-form">
                            <?php $i = 0;
                            foreach ($block->getColumns() as $_column) : ?>
                                <td
                                        data-column="<?= /* @noEscape */ $_column->getId() ?>"
                                    <?= $_column->getHeaderHtmlProperty() ?>
                                >
                                    <?= $_column->getFilterHtml() ?>
                                </td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif ?>
                    </thead>
                <?php endif; ?>
                <tbody>
                <?php if (($block->getCollection()->getSize() > 0) && (!$block->getIsCollapsed())) : ?>
                    <?php foreach ($block->getCollection() as $_index => $_item) : ?>
                        <tr title="<?php $block->escapeHtml($block->getRowUrl($_item)); ?>"
                            <?php if ($_class = $block->getRowClass($_item)) : ?>
                            class="<?= /* @noEscape */ $_class; ?>"
                            <?php endif; ?>
                        >
                            <?php
                            $i = 0;
                            foreach ($block->getColumns() as $_column) :
                                if ($block->shouldRenderCell($_item, $_column)) :
                                    $_rowspan = $block->getRowspan($_item, $_column);
                                    ?>
                                <td <?= ($_rowspan ? 'rowspan="' . $_rowspan . '" ' : '') // @codingStandardsIgnoreLine?>
                                        class="<?= /* @noEscape */ $_column->getCssProperty() ?>
                                    <?= /* @noEscape */ $_column->getId() == 'massaction'
                                            ? 'data-grid-checkbox-cell'
                                            : '' ?>"
                                >
                                    <?= (($_html = $_column->getRowField($_item)) != '' ? $_html : '&nbsp;') // @codingStandardsIgnoreLine?>
                                    </td><?php
                                    if ($block->shouldRenderEmptyCell($_item, $_column)) :
                                        ?>
                                        <td
                                            colspan="<?= /* @noEscape */ $block->getEmptyCellColspan($_item) ?>"
                                            class="last"
                                            >
                                            <?= $block->escapeHtml($block->getEmptyCellLabel()); ?>
                                        </td>
                                    <?php endif;
                                endif;
                            endforeach; ?>
                        </tr>
                        <?php if ($_multipleRows = $block->getMultipleRows($_item)) : ?>
                            <?php foreach ($_multipleRows as $_i) : ?>
                                <tr>
                                    <?php $i = 0;
                                    foreach ($block->getMultipleRowColumns($_i) as $_column) : ?>
                                        <td class="<?= /* @noEscape */ $_column->getCssProperty() ?>
                                            <?= /* @noEscape */ $_column->getId() == 'massaction'
                                            ? 'data-grid-checkbox-cell'
                                            : ''?>"
                                        >
                                            <?=(($_html = $_column->getRowField($_i)) != '' ? $_html : '&nbsp;') // @codingStandardsIgnoreLine?>
                                        </td>
                                    <?php endforeach; ?>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>

                    <?php endforeach; ?>
                <?php elseif ($block->getEmptyText()) : ?>
                    <tr class="data-grid-tr-no-data">
                        <td
                            class="<?= /* @noEscape */ $block->getEmptyTextClass() ?>"
                            colspan="<?= /* @noEscape */ $numColumns ?>"
                        >
                            <?= $block->escapeHtml($block->getEmptyText()); ?>
                        </td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>

        </div>
        <?php if ($block->canDisplayContainer()) : ?>
    </div>
    <script>
        var deps = [];

            <?php if ($block->getDependencyJsObject()) : ?>
        deps.push('uiRegistry');
            <?php endif; ?>

            <?php if (strpos($block->getRowClickCallback(), 'order.') !== false) : ?>
        deps.push('Magento_Sales/order/create/form')
            <?php endif; ?>

        deps.push('mage/adminhtml/grid');

            <?php if (is_array($block->getRequireJsDependencies())) : ?>
                <?php foreach ($block->getRequireJsDependencies() as $dependency) : ?>
        deps.push('<?= $block->escapeJs($dependency); ?>');
                <?php endforeach; ?>
            <?php endif; ?>

        require(deps, function(<?= ($block->getDependencyJsObject() ? 'registry' : '') ?>){
            <?php //TODO: getJsObjectName and getRowClickCallback has unexpected behavior. Should be removed?>

            //<![CDATA[
            <?php if ($block->getDependencyJsObject()) : ?>
            registry.get(
                '<?= /* @noEscape */ $block->getDependencyJsObject() ?>',
                function (<?= /* @noEscape */ $block->getDependencyJsObject() ?>) {
            <?php endif; ?>

                <?= $block->escapeHtml($block->getJsObjectName()); ?>
                    = new varienGrid(<?= /* @noEscape */ $block->jsonEncode($block->getId()) ?>,
                        '<?= $block->escapeHtml($block->getGridUrl()); ?>',
                        '<?= $block->escapeHtml($block->getVarNamePage()); ?>',
                        '<?= $block->escapeHtml($block->getVarNameSort()); ?>',
                        '<?= $block->escapeHtml($block->getVarNameDir()); ?>',
                        '<?= $block->escapeHtml($block->getVarNameFilter()); ?>'
                    );
                <?= $block->escapeHtml($block->getJsObjectName()); ?>
                .useAjax = '<?= /* @noEscape */ $block->getUseAjax() ?>';
                <?php if ($block->getRowClickCallback()) : ?>
                    <?= $block->escapeHtml($block->getJsObjectName()); ?>
                .rowClickCallback = <?= /* @noEscape */ $block->getRowClickCallback() ?>;
                <?php endif; ?>
                <?php if ($block->getCheckboxCheckCallback()) : ?>
                    <?= $block->escapeHtml($block->getJsObjectName()); ?>
                .checkboxCheckCallback = <?= /* @noEscape */ $block->getCheckboxCheckCallback() ?>;
                <?php endif; ?>
                <?php if ($block->getRowInitCallback()) : ?>
                    <?= $block->escapeHtml($block->getJsObjectName()); ?>
                .initRowCallback = <?= /* @noEscape */ $block->getRowInitCallback() ?>;
                    <?= $block->escapeHtml($block->getJsObjectName()); ?>
                .initGridRows();
                <?php endif; ?>
                <?php if ($block->getMassactionBlock() && $block->getMassactionBlock()->isAvailable()) : ?>
                    <?= /* @noEscape */ $block->getMassactionBlock()->getJavaScript() ?>
                <?php endif ?>
                <?= /* @noEscape */ $block->getAdditionalJavaScript(); ?>

                <?php if ($block->getDependencyJsObject()) : ?>
            });
                <?php endif; ?>
            //]]>

        });
    </script>
        <?php endif; ?>
<?php endif ?>
