<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php if ($block->isPossibleOnepageCheckout()):?>
	<div class="row mt-5 mb-3">
                  <div class="col-12 text-md-right">
					    <button type="button"
					            data-role="proceed-to-checkout"
					            title="<?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>"
					            data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
					            class="btn theme_btn btn btn_red action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
					            <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
					        <?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>
					    </button>
				</div>
	</div>
<?php endif?>
