<section class="product_Details pb-0">
    <div class="container">
        <div class="step_section">
            <div class="row">
                <div class="col-12">
                    <ul class="steppper_page">
                        <li class="step_activ"><span class="step_count">1</span><span class="cart_counter_text"><?= __('Shopping Cart') ?></span></li>
                        <li class="step_activ"><span class="step_count">2</span><span class="cart_counter_text"><?= __('Check Out') ?></span></li>
                        <li class=""><span class="step_count">3</span><span class="cart_counter_text"><?= __('Order Completed') ?></span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>