<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$titleHtml = '';
if (trim($block->getPageHeading())){

       $titleHtml= $block->escapeHtml($block->getPageHeading());
}

?>
<?php if ($titleHtml) : ?>
 <div class="row">         
<div class="col-12">
    <div class="my_profile_title"<?php if ($block->getId()) : ?> id="<?= $block->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()) : ?>
            aria-labelledby="<?= $block->escapeHtmlAttr($block->getAddBaseAttributeAria()) ?>"
        <?php endif; ?>>
        	<h4 class=""><?php if($titleHtml=='My Gift Cards'): ?><?php /* @escapeNotVerified */ echo __('Gift Code') ?></h4>
        	<?php else : ?>
        	<?= /* @noEscape */ $titleHtml ?></h4><?php endif; ?>
			<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) { ?>
        <p>Por cada compra realizada acumula puntos que pueden ser canjeados en compras.</p>
<?php } ?></div>
    <?= $block->getChildHtml() ?>
</div>
</div>
<?php endif; ?>
