<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php
$prodid = $_product->getId();
$attribute = $_product->getResource()->getAttribute('free_shipping');
$attribute_value = $attribute->getFrontend()->getValue($_product);

$helper = $this->helper('Magento\Catalog\Helper\Data');
$estimate_time = $helper->getCategory()->getData('estimate_shipping');
//echo "<pre>";
//print_r($helper->getCategory()->getData('estimate_shipping'));die("KK");

if ($attribute_value == "Yes") {?>
    <div class="two"><p class="three"><?php echo "Free Shipping";?></p><?php
  } ?>
  <?php $buttonTitle = __('Add to Cart'); ?>
  <?php if ($_product->isSaleable()) :?>
    <div class="box-tocart product_numbr login_form mt-0">
      <div class="fieldset ">
        <div class="actions button_Section mt-5">
          <h6 class="mb-3"><b><?= __('Choose a delivery method') ?></b></h6>
          <div class="bottom_del_sec">
            <div class="deleviery_section">
             <div class="select_icon_title">
              <img src="<?php echo $this->getViewFileUrl('images/truck.png');?>"><span><?= __('Choose at home') ?></span>
                 <?php if ($_product->getData('free_shipping')): ?>
                    <div class="free_delivery"><?= __('Free Shipping') ?></div>
                 <?php endif?>
            </div>
                <?php if ($estimate_time): ?>
                    <a href="" class="tst_link"><?= $block->escapeHtmlAttr($estimate_time) ?></a>
                <?php endif?>
            <div class="details_btns_container">
             <button type="submit"
             title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
             class="action primary tocart btn details_btn"
             id="product-addtocart-button" disabled>
             <img src="<?php echo $this->getViewFileUrl('images/cart.svg');?>" class="mr-2">
             <span><?= $block->escapeHtml($buttonTitle) ?></span>
           </button>
           <?= $block->getChildHtml('', true) ?>
         </div>
       </div>
       <div class="deleviery_section">
         <div class="select_icon_title">
          <img src="<?php echo $this->getViewFileUrl('images/home.png');?>"><span><?= __('Pick up in store') ?></span>
        </div>
        <a class="tst_link"><?= __('Units Available: 10+') ?></a>
        <div class="details_btns_container" data-mage-init='{"pickupstore_popup": {}}'>
          <a class="btn details_btn btn_black_bg" id="click-me" ><img src="<?php echo $this->getViewFileUrl('images/btn_home.png');?>"  class="mr-2"><?= __('Free withdrawal in store') ?></a>
          <a class="btn qty-list border_btn mt-3" >
              <img src="<?php echo $this->getViewFileUrl('images/cart_bg.png');?>"  class="mr-2"><?= __('See Available') ?>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
  {
    "#product_addtocart_form": {
    "Magento_Catalog/js/validate-product": {}
  }
}
</script>

<div id="popup-modal" class="row" style="display: none">
    <% if (posts) { %>
    <div class="location_list" store_id= "<%= posts.storeid %>">
            <% if (posts.location_info) { %>
                <% _.each(posts.location_info.location_id, function(text,value) { %>
                    <div class="location" store_id= "<%= posts.storeid %>">
                        <% if (posts.location_info.location_img_url) { %>
                        <div class="location-info-row" >
                            <div class="store_img" >
                                <img src="<%= posts.location_info.location_img_url[value] %>" />
                            </div>
                        <% } %>
                        <% if (posts.location_info) { %>
                            <div class="location-info" location-id="<%= posts.location_info.location_id[value] %>">
                                <% if (posts.location_info.location_name) { %>
                                <div class="location-name">
                                    <%= posts.location_info.location_name[value] %>
                                </div>
                                <% } %>
                                <% if (posts.location_info.location_address) { %>
                                    <div class="location-address">
                                        <%= posts.location_info.location_address[value] %>
                                    </div>
                                <% } %>
                                <% if (posts.location_info.location_schedule) { %>
                                    <div class="location-time">
                                        <%= posts.location_info.location_schedule %>
                                    </div>
                                <% } %>
                                <% if (posts.location_info.location_phone_num) { %>
                                    <div class="location-contact">
                                        <%= posts.location_info.location_phone_num[value] %>
                                    </div>
                                <% } %>
                            </div>
                        </div>
                        <% } %>
                        <% if (posts.stock_info) { %>
                            <div class="stock-info">
                                <% if (posts.stock_info.status[value] == 1) { %>
                                    <div class="disponit-icon"> <i class="fa fa-check" aria-hidden="true"></i> Disponible en la tienda</div>
                                <div class="details_btns_container">
                                    <button type="submit"
                                            title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                                            class="action primary tocart btn popup-addtocart"
                                            id="addtocart-button-popup" disabled>
                                        <img src="<?php echo $this->getViewFileUrl('images/cart.svg');?>" class="mr-2">
                                        <span><?= $block->escapeHtml($buttonTitle) ?></span>
                                    </button>
                                    <?= $block->getChildHtml('', true) ?>
                                </div>
                                <% } %>
                                <% if (posts.stock_info.status[value] == 0) { %>
                                    <div class="no-disponit-icon"><i class="fa fa-times" aria-hidden="true"></i> No Disponible </div>
                                <% } %>
                                <% if (!posts.stock_info.status[value]) { %>
                                    <div class="no-disponit-icon"><i class="fa fa-times" aria-hidden="true"></i> No Disponible </div>
                                <% } %>

                            </div>
                        <% } %>
                    </div>

                <% }) %>
            <% } %>
        <% } %>
    </div>
</div>