<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
?>
<a href="#"
   title="<?= $block->escapeHtml(__('Remove item')) ?>"
   class="Remove_de action action-delete remove_from"
   data-post='<?= /* @escapeNotVerified */ $block->getDeletePostJson() ?>'>
    <i class="far fa-trash-alt"></i>
</a>
