
<section class="banner_Section product_Details_bg">
            <div class="row">
              <div class="col-12">
                <div class="pre_order_content">
                  <div class="section_title text-center mb-0">
                    <h2><?php echo $block->escapeHtml(__('Product Detail')); ?></h2>
                  </div>
                </div>
              </div>  
            </div>
      </section>
    <!-- banner section End-->
    <!-- showing result section -->
    <!-- <section class="showing_result">
            <div class="row align-items-center">
              <div class="col-12 col-md-6">
                <ul class="breadcum_links">
                  <li><a href="<?php echo $this->getUrl() ?>"><?php echo $block->escapeHtml(__('Home')); ?></a></li>
                  <li>></li>
                  <li>Product Detail</li>
                  <li></li>
                </ul>
              </div>
          </div>
    </section> -->