<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_MultiInventory
 */
?>
<?php
/** @var $block \Amasty\MultiInventory\Block\Script\Google */
?>

<?php if ($block->isAddressSuggestionEnabled()) : ?>
    <script src="https://maps.googleapis.com/maps/api/js?key=<?= $block->escapeHtml(
        $block->getApiKey()
    ); // @codingStandardsIgnoreLine?>
    &signed_in=true&libraries=places" async defer>

</script>
<?php endif?>

<script>
    window.isAddressSuggestionEnabled = <?= (int)$block->isAddressSuggestionEnabled(); ?>;
</script>
