<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
 <div class="tab-content profile_tab_content gray_textbox" id="v-pills-tabContent">
    <div class=" show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
               <form  class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
                    <fieldset class="fieldset info">
                    <?= $block->getBlockHtml('formkey') ?>
                                
                                                  <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getCustomer())->toHtml() ?>
                                 <?php if($myCustomAttribute = ($block->getCustomer()->getCustomAttribute('contact'))) : ?>
                                         <div class="row">
                                            <div class="col-lg-8">
                                               <div class="form-group">
                                                  <label><?= $block->escapeHtml(__('Contact Number')) ?></label>
                                                  <input type="text" minlength="8" maxlength="15" placeholder="Contact Number"  onKeyDown="qtyKeyDown(event);" title="<?= $block->escapeHtmlAttr(__('Contact')) ?>" id="contact"   name="contact" class="form-control input_box" value="<?php echo $myCustomAttribute->getValue(); ?>"  data-validate="{required:true}" >
                                               </div>
                                            </div>
                                         </div>
                                         <?php else :?>
                                         <div class="row">
                                            <div class="col-lg-8">
                                               <div class="form-group">
                                                  <label><?= $block->escapeHtml(__('Contact Number')) ?></label>
                                                  <input type="text" placeholder="Contact Number" title="<?= $block->escapeHtmlAttr(__('Contact')) ?>" id="contact"   name="contact" class="form-control input_box" value=" " data-validate="{required:true}" >
                                               </div>
                                            </div>
                                         </div>
                                        <?php endif ?> 
                                          <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
                                          <?php if ($_gender->isEnabled()) : ?>
                                           <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
                                         <?php endif ?>
                                         <div class="row">
                                            <div class="col-12 col-md-3">
                                               <div class="radio mb-3">
                                                  <input type="checkbox"  name="change_email" id="change-email" data-role="change-email" value="1" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" >
                                                  <label for="test1"><?= $block->escapeHtml(__('Change Email')) ?></label>
                                               </div>
                                            </div>
                                            <div class="chagepass">
                                               <div class="radio mb-3">
                                                  <input type="checkbox"  name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()) : ?> checked="checked"<?php endif; ?> class="checkbox" >
                                                  <label for="test2"><?= $block->escapeHtml(__('Change Password')) ?></label>
                                               </div>
                                            </div>
                                         </div>   
                             </fieldset>
        <fieldset class="fieldset password" data-container="change-email-password">
                             <div class="row mt-4">
                                      <div class="col-12">
                                         <h4 class="page_t"><?= $block->escapeHtml(__('Change Email and Password')) ?></h4>
                                      </div>
                            </div>
                                   <div class="row">
                                            <div class="col-lg-8">
                                               <div class="field email required form-group" data-container="change-email">
                                                  <label><?= $block->escapeHtml(__('Email')) ?></label>
                                                  <input type="email" name="email" id="email"  class="input-text form-control input_box" autocomplete="email" data-input="change-email" value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}" >
                                               </div>
                                            </div>
                                         </div>
                                         <div class="row">
                                            <div class="col-lg-8">
                                               <div class="field password current required form-group">
                                                  <label><?= $block->escapeHtml(__('Current Password')) ?></label>
                                                  <input type="password" name="current_password" id="current-password" data-input="current-password" placeholder="Current Password" autocomplete="off"  class="input-text form-control input_box" >
                                               </div>
                                            </div>
                                         </div>

                                         <div class="row">
                                            <div class="col-lg-8">
                                               <div class="field new password required form-group" data-container="new-password">
                                                  <label><?= $block->escapeHtml(__('New Password')) ?></label>
                                                  <input type="password"  name="password" placeholder="New Password"  class=" input-text form-control input_box" id="password"
                                                    data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                                                    data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                                                    data-input="new-password"
                                                    data-validate="{required:true, 'validate-customer-password':true}"
                                                    autocomplete="off" >

                                                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                                                            <div id="password-strength-meter" class="password-strength-meter">
                                                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                                                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                                                    <?= $block->escapeHtml(__('No Password')) ?>
                                                                </span>
                                                            </div>
                                                    </div>

                                               </div>
                                            </div>
                                         </div>
                                          <div class="row">
                                            <div class="col-lg-8">
                                               <div class="field confirm password required form-group" data-container="confirm-password">
                                                  <label><?= $block->escapeHtml(__('Confirm New Password')) ?></label>
                                                      <input type="password" placeholder="Confirm New Password" name="password_confirmation"  class="input-text form-control input_box" id="password-confirmation"
                                                        data-input="confirm-password"
                                                        autocomplete="off" >
                                               </div>
                                            </div>
                                         </div>

            </fieldset>                           
            <?= $block->getChildHtml('form_additional_info') ?>
            <div class="actions-toolbar">
                <div class="primary">
                    <div class="row">
                        <div class="col-12">
                                <button type="submit" class="action save primary btn theme_btn mt-3" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"><i class="fas fa-pencil-alt pr-2"></i><?= $block->escapeHtml(__('Update Profile')) ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
