<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<div class="section_title">
                <h2><?= $block->escapeHtml(__('Set a New Password')) ?></h2>
                <span class="bottom_line"></span>
            </div>

<form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['token' => $block->getResetPasswordLinkToken()]])) ?>"
      method="post"
        <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
      id="form-validate"
      class="form password reset"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset login login_form forgot-custom-pass" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            
            <div class="control form-group">
                <input type="password" placeholder="<?= $block->escapeHtml(__('New Password')) ?>" class="input-text form-control input_box" name="password" id="password"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <span class="form_imgs"><img src="<?php echo $block->getViewFileUrl('images/form_key.png'); ?>"></span>
                
            </div>
        </div>
        <div class="field confirmation required">
            <div class="control form-group">
                <input type="password" placeholder="<?= $block->escapeHtml(__('Confirm New Password')) ?>" class="input-text form-control input_box" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
                <span class="form_imgs"><img src="<?php echo $block->getViewFileUrl('images/form_key.png'); ?>"></span>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary btn theme_btn"><span><?= $block->escapeHtml(__('Set a New Password')) ?></span></button>
        </div>
    </div>
</form>
