  <?php
  /**
   * @author Amasty Team
   * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
   * @package Amasty_AdvancedReview
   */
  ?>
  <?php
  //rewrite file Magento_Review::product/view/list.phtml
  // phpcs:ignoreFile

  /** @var Magento\Review\Block\Product\View\ListView $block */
  $displayedCollection = $block->getReviewsCollection();
  $_items = $displayedCollection->getItems();
  $format = $block->getDateFormat() ?: \IntlDateFormatter::MEDIUM;

  /** @var \Amasty\AdvancedReview\Helper\BlockHelper $advancedHelper */
  $advancedHelper = $block->getData('advanced-review-helper');

  $isFilterApplied = $displayedCollection->getFlag(\Amasty\AdvancedReview\Model\Toolbar\Applier::COLLECTION_FLAG);
  ?>

  <?php if (count($_items) || $isFilterApplied) : ?>
    <div id="reviews">
      <div class="block review-list product-review-container" id="customer-reviews"> <div class="review_titles">
        <h4>
          <?= /* @noEscape */  __('Customer Reviews')?>
        </h4>
      </div>   <div class="review_table">
        <div class="row">
         <div class="col-12 col-md-8 col-lg-9">
           <div class="review_details">
            
            <div class="amreview-info-wrapper" data-amreview-js="review-container">
              <?= /* @noEscape */ $advancedHelper->getReviewsSummaryHtml($block->getProduct(), $displayedCollection) ?>
              
            </div>
          </div></div><div class="col-12 col-md-4 col-lg-3"><a class="btn review_btn" type="button">Escribir Comentario</a></div>
        </div>
        <?php if (count($_items)): ?>

          <div class="row align-items-center">
            <div class="col-12 col-md-9">
              <p class="mb-0"></p>
            </div>
            <div class="col-12 col-md-3">
              <?= /* @noEscape */ $advancedHelper->getReviewToolbarHtml($displayedCollection); ?>
            </div>
          </div>
        <?php endif; ?>


      </div>
      

      

      
      
      <div class="amrev-items-block block-content" data-amload-js="container">
        <?php if (count($_items)): ?>
          <ol class="items amreview-review-items">
            <?php foreach ($_items as $review) : ?>
              <li class="super_div item review-item amreview-review-wrapper"
              data-amreview-js="review-entity"
              data-amreview-id="<?= (int)$review->getId() ?>"
              itemscope itemprop="review"
              itemtype="http://schema.org/Review">
              <div class="row">
                <div class="col-12 col-md-8 col-lg-9 review-1">
                  <div class="review-details amreview-author-details">
                    <div class="amreview-wrap">
                      <p class="amreview-author" itemprop="author">
                        <?= $block->escapeHtml($review->getNickname()) ?>
                      </p>
                      <?= $advancedHelper->getVerifiedBuyerHtml($review) ?>
                      
                      <?= $advancedHelper->getRecommendedHtml($review) ?>
                    </div>
                  </div>

                  <div class="amreview-description-wrap" data-amreview-js="description-wrap">
                    <div class="amrev-desc-title">
                      <span class="amreview-title-review" itemprop="name">
                        <?= $block->escapeHtml($review->getTitle()) ?>
                      </span>
                      
                    </div>
                    <?php if (count($review->getRatingVotes())) : ?>
                      <?php foreach ($review->getRatingVotes() as $_vote) : ?>
                        <span class="amreview-rating-label"><?= $block->escapeHtml($_vote->getRatingCode()) ?></span>
                        <div class="amstars-rating-container -small"
                        <?php $stars = $_vote->getValue(); ?>
                        title="<?= $block->escapeHtml($stars > 1 ? __('%1 stars', $stars) : __('%1 star', $stars)) ?>"
                        itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                        <meta itemprop="worstRating" content="1"/>
                        <meta itemprop="bestRating" content="100"/>
                        <p class="amstars-stars"
                        style="width:<?= $block->escapeHtml($_vote->getPercent()) ?>%">
                        <span itemprop="ratingValue" class="hidden">
                          <?= $block->escapeHtml($_vote->getPercent()) ?>%
                        </span>
                      </p>
                    </div>
                  <?php endforeach; ?>
                <?php endif; ?>
                <div class="amreview-description amshowmore-container"
                data-mage-init='{"amShowMore": {"maxCharaters": 500}}'
                itemprop="description">
                <span class="amreview-text amshowmore-text" data-amshowmore-js="text"><?= $block->escapeHtml($review->getDetail()); ?></span>
                <?= /* @noEscape */ $advancedHelper->getReviewImagesHtml($review->getId()) ?>
              </div>

              <?php $answer = $advancedHelper->getReviewAnswerHtml($review); ?>
              <?php if ($answer) : ?>
                <div class="amreview-adminanswer-block">
                  <p class="amreview-title">
                    <?= $block->escapeHtml(__('Response from store')); ?>
                  </p>
                  <div class="amreview-text review-details">
                    <?= /* @noEscape */ nl2br($block->escapeHtml($answer)); ?>
                  </div>
                </div>
              <?php endif; ?>
              <div class="amrev-comment-toolbar <?= !$advancedHelper->isCommentsAllowed() ? '-nocomments' : '' ?>">
                <?php if ($advancedHelper->isCommentsAllowed()) : ?>
                  <div class="amrev-reply">
                    <button class="amrev-repbtn" data-amreview-js="reply">
                      <?= $block->escapeHtml(__('Reply')); ?>
                    </button>
                  </div>
                  <div class="amrev-comment">
                    <button class="amrev-combtn" data-amreview-js="comments">
                      <?= $block->escapeHtml(__('Comments')); ?>
                      (<span data-review-js="comment-qty">0</span>)
                    </button>
                  </div>
                <?php endif; ?>
                <?= $advancedHelper->getHelpfulHtml($review) ?>
              </div>

              <?php $like = $review->getData('like_about'); ?>
              <?php $disLike = $review->getData('not_like_about'); ?>
              <?php if ($advancedHelper->isProsConsEnabled() && ($like || $disLike)) : ?>
              <div class="amreview-proscons-container">
                <?php if ($like) : ?>
                  <p class="amreview-proscons -like">
                    <?= /* @noEscape */ nl2br($block->escapeHtml($like)); ?>
                  </p>
                <?php endif; ?>
                <?php if ($disLike) : ?>
                  <p class="amreview-proscons -dislike">
                    <?= /* @noEscape */ nl2br($block->escapeHtml($disLike)); ?>
                  </p>
                <?php endif; ?>
              </div>
            <?php endif; ?>

            <div class="amrev-comment-block"
            data-amreview-js="comment-block-review-id-<?= (int)$review->getId() ?>">
          </div>
        </div>


      </div>
      <div class="col-12 col-md-4 col-lg-3 review-2">
        <p class="amreview-date hence_right">
          <time class="review-details-value"
          itemprop="datePublished"
          datetime="<?= $block->escapeHtml($block->formatDate($review->getCreatedAt(), $format)) ?>">
          <?= $block->escapeHtml($block->formatDate($review->getCreatedAt(), $format)) ?>
        </time>
      </p>
      <span class="hence_right">
        <?= $advancedHelper->getHelpfulHtml($review, true) ?>
      </span>
    </div>
    
    
  </div>
</li>
<?php endforeach; ?>
</ol>
<div class="toolbar review-toolbar amreview-toolbar-wrap">
 
</div>

<?php endif; ?>
</div>
</div>
</div>
<?php endif; ?>
<script>
 require(
   [
   'jquery',
   'Magento_Ui/js/modal/modal'
   ],
   function (
     $,
     modal
     ) {
     var modaloption = {
       type: 'popup',
       modalClass: 'modal-popup custom-review',
       responsive: true,
       innerScroll: true,
       clickableOverlay: true,
     };
      jQuery(document).ready(function(){
     var callforoption = modal(modaloption, $('.callfor-popup'));
     jQuery("a.btn.review_btn").on('click',function(){ 
              console.log("faasdfaaaaaaaaaaaadsf");
             // $.fn.bsModal = $.fn.modal.noConflict();
              jQuery.noConflict();
              jQuery('.callfor-popup').modal('openModal');
              jQuery('.overlay2').addClass("show");   
              
        //remove the padding right and modal-open class from the body tag which bootstrap adds when a modal is shown
        
        //$('body').removeClass("modal-open")
      });
     jQuery(".custom-review button.action-close.close span").on('click',function(){ 
      jQuery('.overlay2').removeClass("show");
    });
     });
   }
   );
 </script>
 <script>
  require(['jquery', 'simpleLoadMore'], function($, simpleLoadMore) {
    $('ol.items.amreview-review-items').simpleLoadMore({
     item: 'li',
     count: 5,
     btnHTML:'<a class="custom_button_review_load" type="button"><span class="btn review_btn load-more__btn">MOSTRAR MÁS COMENTARIOS</span></a>'

   });
  });
</script>