<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

// phpcs:disable Magento2.Security.IncludeFile.FoundIncludeFile
// phpcs:disable PSR2.Methods.FunctionCallSignature.SpaceBeforeOpenBracket
?>
<?php if ($block->getCollection()->getSize()) :?>
    <div class="row toolbar toolbar-products align-items-center" data-mage-init='<?= /* @noEscape */ $block->getWidgetOptionsJson() ?>'>
	<div class="col-4 col-lg-6">
		<?php if ($block->isExpanded()) :?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>
	</div>
	<div class="col-4 col-lg-6 text-md-right pagination_div">
		<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

		<?= $block->getPagerHtml() ?>
		
		<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
		

        <?php if ($block->isExpanded()) :?>
			<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
		<?php endif; ?>
    </div>
    <div class="col-4 text-md-right filter_mobile">
    <div class="filter-btn common-transition"><a href="javascript:void(0);">Filtro</a></div>
</div>
</div>
<div class="mobile-result row">
	<div class="col-12">
		<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

</div>
</div>
<?php endif ?>
