<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
<section class="showing_result">
		<?= $block->getToolbarHtml() ?>
</section>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    }
    /**o
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
	<section class="back_white_titlw product_section">
	<!--<div class="filter_m desktop_visible_one" style="cursor: pointer;" onclick="nav2()"><i class="fas fa-stream"></i></div>-->
		<?php if($viewMode == "grid") { ?>
			<div class="product_listing products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
				<div class="row products list items product-items">
					<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
					<?php foreach ($_productCollection as $_product) :?>
					<div class="col-lg-3 col-md-4 col-6 item product product-item">
						<div class="product_div product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
							<?php
							$productImage = $block->getImage($_product, $imageDisplayArea);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<?php // Product Image ?>
							<a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
							   class="product_img product photo product-item-photo"
							   tabindex="-1">
								<?= $productImage->toHtml() ?>
							</a>
							<div class="about_pre_product product details product-item-details">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<strong class="product name product-item-name">
									<a class="product-item-link"
									   href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
										<h5><?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h5>
									</a>
								</strong>
								<?php $orgprice = $_product->getPrice();
								$specialprice = $_product->getSpecialPrice();
								$specialfromdate = $_product->getSpecialFromDate();
								$specialtodate = $_product->getSpecialToDate();
								$today = time();
								if (!$specialprice)
								  $specialprice = $orgprice;
								if ($specialprice< $orgprice) {
									if ((is_null($specialfromdate) &&is_null($specialtodate)) || ($today >= strtotime($specialfromdate) &&is_null($specialtodate)) || ($today <= strtotime($specialtodate) &&is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) { ?>
										<div class="offer">         
											<span class="offer_title"><font style="vertical-align: inherit;"><?= $block->escapeHtml(__('Offer')) ?></font></span>
										</div>
									<?php } 
								} ?>
								<?php if($_product->getNewProduct())
								{ ?>
									<div class="new_products">          
										<span class="new_title"><font style="vertical-align: inherit;"><?= $block->escapeHtml(__('New')) ?> </font></span>
									</div>
								<?php } ?>
								<?php if ($_product->getAttributeText('manufacturer')) { ?>
								<div class ="custom-merge-div">
								<?php if ($_product->getAttributeText('manufacturer')) { ?>
								<div class="custom-brand-name">
								<?php


									$manufacturerName = $_product->getAttributeText('manufacturer');
									$manufacturerName = strtolower($manufacturerName);


									$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
									$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
									$connection = $resource->getConnection();
									$tableName = $resource->getTableName('emizentech_shopbybrand_items'); //gives table name with prefix

									//Select Data from table
									$sql = "Select name, logo FROM " . $tableName;
									$result = $connection->fetchAll($sql); // gives associated array, table fields as key in array.

									$img = '';

									foreach($result as $res) {
										$brname = strtolower($res['name']);
										if($brname == $manufacturerName) {
											if($res['logo']) {
												$img = $res['logo'];
											} else {
												$img = '';
											}
										}
									}
									//print_r($img);
									if($img) {
								?>
									<img class="img-responsive" src="<?php echo  $this->getUrl().'pub/media/'.$img ?>" alt="<?php echo $manufacturerName; ?>" height="60px" width="60px" />
								<?php } else { ?>
									<span class="br_name"><?php echo $manufacturerName; ?></span>
								<?php } ?>
								</div>
								<?php } ?>
								<div class="custom_rating_category" style="display: block!important;">
								<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
								</div>
								</div>
								<?php } ?>
								<?php if ($_product->isAvailable()) :?>
													<div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
								<?php endif; ?>
					
								<div class="butt_price_section">
								<?= /* @noEscape */ $block->getProductPrice($_product) ?>
								<?php $orgprice = $_product->getPrice();
								$specialprice = $_product->getSpecialPrice();
								$specialfromdate = $_product->getSpecialFromDate();
								$specialtodate = $_product->getSpecialToDate();
								$today = time();
								if (!$specialprice)
								  $specialprice = $orgprice;
								if ($specialprice< $orgprice) {
									if ((is_null($specialfromdate) &&is_null($specialtodate)) || ($today >= strtotime($specialfromdate) &&is_null($specialtodate)) || ($today <= strtotime($specialtodate) &&is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) {
										$savingpct = number_format((float)(100*(($orgprice - $specialprice)/$orgprice)), 0);?>
										<div class="money_saved">
											<span class="price-save-label"><?= __('Save') ?> </span>
											<span class="price-save-percent"><?php echo " ".$savingpct." %"?></span>
										</div>
									<?php }
								}?>
								<?php $block->getProductDetailsHtml($_product) ?>
							
								<div class="product-item-inner display_hvr">
									<div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
										<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
											<?php if ($_product->isSaleable()) :?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form"
													  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
													  action="<?= $block->escapeUrl($postParams['action']) ?>"
													  method="post">
													<input type="hidden"
														   name="product"
														   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
													<input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
														   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
													<?= $block->getBlockHtml('formkey') ?>
	<!-- <a class="btn theme_btn img_btn bss-quickview hovercart" title="<?php //echo $block->escapeHtml(__('Quick View')); ?>"  data-toggle="modal" data-target="#product_quickview" data-quickview-url="" href="javascript:void(0)"> <i class="fas fa-eye"></i><?php// echo $block->escapeHtml(__('Quick View')); ?></a> -->

													<button type="submit"
															title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
															class="btn theme_btn img_btn action tocart primary">
															<img src="<?php echo $this->getViewFileUrl('images/cart.svg');?>" class="mr-2">
														<span><?= $block->escapeHtmlAttr(__('Add to Cart')) ?></span>
													</button>
												</form>
											<?php else :?>
												<?php if ($_product->isAvailable()) :?>
													<div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
												<?php else :?>
													<div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									</div>
								</div>
								</div>
							</div>
						</div>
					</div>
					<?php endforeach; ?>
				</div>
			</div>
			<div class="row align-items-center bottom-toolbar" style="display: none;">
				<?= $block->getToolbarHtml() ?>
			</div>
			<?php if (!$block->isRedirectToCartEnabled()) :?>
					<script type="text/x-magento-init">
					{
						"[data-role=tocart-form], .form.map.checkout": {
							"catalogAddToCart": {
								"product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
							}
						}
					}
					</script>
			<?php endif; ?>
		<?php } else { ?>
			<div class="listing_new_cus">
			    <?php foreach ($_productCollection as $_product) :?>
					<div class="item product product-item listing_pr">
					<div class="row">
						<?php $orgprice = $_product->getPrice();
								$specialprice = $_product->getSpecialPrice();
								$specialfromdate = $_product->getSpecialFromDate();
								$specialtodate = $_product->getSpecialToDate();
								$today = time();
								if (!$specialprice)
								  $specialprice = $orgprice;
								if ($specialprice< $orgprice) {
									if ((is_null($specialfromdate) &&is_null($specialtodate)) || ($today >= strtotime($specialfromdate) &&is_null($specialtodate)) || ($today <= strtotime($specialtodate) &&is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) { ?>
										<div class="offer">         
											<span class="offer_title"><font style="vertical-align: inherit;"><?= $block->escapeHtml(__('Offer')) ?> </font></span>
										</div>
									<?php } 
								} ?>
								<?php if($_product->getNewProduct())
								{ ?>
									<div class="new_products">          
										<span class="new_title"><font style="vertical-align: inherit;"><?= $block->escapeHtml(__('New')) ?> </font></span>
									</div>
								<?php } ?>
								
						<div class="col-12 col-lg-3 col-md-5">
							<?php
							$productImage = $block->getImage($_product, $imageDisplayArea);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<?php // Product Image ?>
							<a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
							   class="listing_img product photo product-item-photo"
							   tabindex="-1">
								<?= $productImage->toHtml() ?>
							</a>
						</div>
						<div class="col-12 col-lg-6 col-md-7">
							<div class="about_pre_product">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<strong class="product name product-item-name" style="display: inline-block;">
									<a class="product-item-link"
									   href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
										<h5><?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h5>
									</a>
								</strong>
								<?php if ($_product->getAttributeText('manufacturer')) { ?>
								<div class ="custom-merge-div">
								<?php if ($_product->getAttributeText('manufacturer')) { ?>
								<div class="custom-brand-name">
								<?php


									$manufacturerName = $_product->getAttributeText('manufacturer');
									$manufacturerName = strtolower($manufacturerName);


									$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
									$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
									$connection = $resource->getConnection();
									$tableName = $resource->getTableName('emizentech_shopbybrand_items'); //gives table name with prefix

									//Select Data from table
									$sql = "Select name, logo FROM " . $tableName;
									$result = $connection->fetchAll($sql); // gives associated array, table fields as key in array.

									$img = '';

									foreach($result as $res) {
										$brname = strtolower($res['name']);
										if($brname == $manufacturerName) {
											if($res['logo']) {
												$img = $res['logo'];
											} else {
												$img = '';
											}
										}
									}
									//print_r($img);
									if($img) {
								?>
									<img class="img-responsive" src="<?php echo  $this->getUrl().'pub/media/'.$img ?>" alt="<?php echo $manufacturerName; ?>" height="60px" width="60px" />
								<?php } else { ?>
									<span class="br_name"><?php echo $manufacturerName; ?></span>
								<?php } ?>
								</div>
								<?php } ?>
								<div class="custom_rating_category" style="display: block!important;">
								<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
								</div>
								</div>
							<?php } ?>
                                <?php if ($_product->isAvailable()) :?>
                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                <?php endif; ?>
								<?php if ($showDescription) :?>
									<div class="product description product-item-description">
										<?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
										   title="<?= /* @noEscape */ $_productNameStripped ?>"
										   class="action more"><h6><?= $block->escapeHtml(__('Learn More')) ?></h6></a>
									</div>
								<?php endif; ?>
							</div>
						</div>
						<?php 
							$attribute = $_product->getResource()->getAttribute('free_shipping');
							$attribute_value = $attribute ->getFrontend()->getValue($_product);
							if ($attribute_value == "Yes")
							{?>
							<div class="two"><p class="three"><?php echo "Free Shipping";?></p><?php 
							 } ?>
						<div class="col-12 col-md-7 offset-md-5 offset-lg-0 col-lg-3">
							<div class="custom-price-stock-list">
							
								<?= /* @noEscape */ $block->getProductPrice($_product) ?>
								<?php $orgprice = $_product->getPrice();
								$specialprice = $_product->getSpecialPrice();
								$specialfromdate = $_product->getSpecialFromDate();
								$specialtodate = $_product->getSpecialToDate();
								$today = time();
								if (!$specialprice)
								  $specialprice = $orgprice;
								if ($specialprice< $orgprice) {
									if ((is_null($specialfromdate) &&is_null($specialtodate)) || ($today >= strtotime($specialfromdate) &&is_null($specialtodate)) || ($today <= strtotime($specialtodate) &&is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) {
										$savingpct = number_format((float)(100*(($orgprice - $specialprice)/$orgprice)), 0);?>
										<div class="money_saved">
											<span class="price-save-label"><?= __('Save') ?> </span>
											<span class="price-save-percent"><?php echo " ".$savingpct." %"?></span>
										</div>
									<?php }
								}?>
							 </div>
							<div class="carts_btns">
								<div class="product-item-inner">
									<div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
										<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
											<?php if ($_product->isSaleable()) :?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form"
													  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
													  action="<?= $block->escapeUrl($postParams['action']) ?>"
													  method="post">
													<input type="hidden"
														   name="product"
														   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
													<input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
														   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
													<?= $block->getBlockHtml('formkey') ?>
													<!-- <a class="btn theme_btn img_btn bss-quickview hovercart" title="<?php //echo $block->escapeHtml(__('Quick View')); ?>"  data-toggle="modal" data-target="#product_quickview" data-quickview-url="" href="javascript:void(0)"><i class="fas fa-eye"></i>
													<?php //echo $block->escapeHtml(__('Quick View')); ?></a> -->
													<button type="submit"
															title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
															class="btn theme_btn img_btn mb-3 hvr-wobble-vertical action tocart primary">
															<img src="<?php echo $this->getViewFileUrl('images/cart.svg');?>" class="mr-2">
														<span><?= $block->escapeHtmlAttr(__('Add to Cart')) ?></span>
													</button>
													
												</form>
											<?php else :?>
												<?php if ($_product->isAvailable()) :?>
													<div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
												<?php else :?>
													<div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php endforeach; ?>
			</div>
			<div class="row align-items-center bottom-toolbar" style="display: none;">
				<?= $block->getToolbarHtml() ?>
			</div>
			<?php if (!$block->isRedirectToCartEnabled()) :?>
				<script type="text/x-magento-init">
				{
					"[data-role=tocart-form], .form.map.checkout": {
						"catalogAddToCart": {
							"product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
						}
					}
				}
				</script>
			<?php endif; ?>
		<?php } ?>
	</section>
<?php endif; ?>
